# Generated by Django 2.2.2 on 2022-07-17 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('symbol', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('phonenumber', models.IntegerField()),
                ('select', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='product_image/')),
            ],
        ),
    ]
